# Generated by Django 5.0.3 on 2024-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='lorem ipsum', max_length=1000),
        ),
    ]
